/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as SchemasRouteImport } from './routes/schemas'
import { Route as ConfigsRouteImport } from './routes/configs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemaIndexRouteImport } from './routes/schema/index'
import { Route as SchemaLayoutRouteImport } from './routes/schema/_layout'
import { Route as ConfigCompareRouteImport } from './routes/config/compare'
import { Route as ConfigNameVersionRouteImport } from './routes/config/$name/$version'

const SchemaRouteImport = createFileRoute('/schema')()

const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasRoute = SchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsRoute = ConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaIndexRoute = SchemaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchemaRoute,
} as any)
const SchemaLayoutRoute = SchemaLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => SchemaRoute,
} as any)
const ConfigCompareRoute = ConfigCompareRouteImport.update({
  id: '/config/compare',
  path: '/config/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigNameVersionRoute = ConfigNameVersionRouteImport.update({
  id: '/config/$name/$version',
  path: '/config/$name/$version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configs': typeof ConfigsRoute
  '/schemas': typeof SchemasRoute
  '/wizard': typeof WizardRoute
  '/config/compare': typeof ConfigCompareRoute
  '/schema': typeof SchemaLayoutRoute
  '/schema/': typeof SchemaIndexRoute
  '/config/$name/$version': typeof ConfigNameVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configs': typeof ConfigsRoute
  '/schemas': typeof SchemasRoute
  '/wizard': typeof WizardRoute
  '/config/compare': typeof ConfigCompareRoute
  '/schema': typeof SchemaIndexRoute
  '/config/$name/$version': typeof ConfigNameVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configs': typeof ConfigsRoute
  '/schemas': typeof SchemasRoute
  '/wizard': typeof WizardRoute
  '/config/compare': typeof ConfigCompareRoute
  '/schema': typeof SchemaRouteWithChildren
  '/schema/_layout': typeof SchemaLayoutRoute
  '/schema/': typeof SchemaIndexRoute
  '/config/$name/$version': typeof ConfigNameVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configs'
    | '/schemas'
    | '/wizard'
    | '/config/compare'
    | '/schema'
    | '/schema/'
    | '/config/$name/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configs'
    | '/schemas'
    | '/wizard'
    | '/config/compare'
    | '/schema'
    | '/config/$name/$version'
  id:
    | '__root__'
    | '/'
    | '/configs'
    | '/schemas'
    | '/wizard'
    | '/config/compare'
    | '/schema'
    | '/schema/_layout'
    | '/schema/'
    | '/config/$name/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigsRoute: typeof ConfigsRoute
  SchemasRoute: typeof SchemasRoute
  WizardRoute: typeof WizardRoute
  ConfigCompareRoute: typeof ConfigCompareRoute
  SchemaRoute: typeof SchemaRouteWithChildren
  ConfigNameVersionRoute: typeof ConfigNameVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas': {
      id: '/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs': {
      id: '/configs'
      path: '/configs'
      fullPath: '/configs'
      preLoaderRoute: typeof ConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema/': {
      id: '/schema/'
      path: '/'
      fullPath: '/schema/'
      preLoaderRoute: typeof SchemaIndexRouteImport
      parentRoute: typeof SchemaRoute
    }
    '/schema/_layout': {
      id: '/schema/_layout'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaLayoutRouteImport
      parentRoute: typeof SchemaRoute
    }
    '/config/compare': {
      id: '/config/compare'
      path: '/config/compare'
      fullPath: '/config/compare'
      preLoaderRoute: typeof ConfigCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/$name/$version': {
      id: '/config/$name/$version'
      path: '/config/$name/$version'
      fullPath: '/config/$name/$version'
      preLoaderRoute: typeof ConfigNameVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SchemaRouteChildren {
  SchemaLayoutRoute: typeof SchemaLayoutRoute
  SchemaIndexRoute: typeof SchemaIndexRoute
}

const SchemaRouteChildren: SchemaRouteChildren = {
  SchemaLayoutRoute: SchemaLayoutRoute,
  SchemaIndexRoute: SchemaIndexRoute,
}

const SchemaRouteWithChildren =
  SchemaRoute._addFileChildren(SchemaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigsRoute: ConfigsRoute,
  SchemasRoute: SchemasRoute,
  WizardRoute: WizardRoute,
  ConfigCompareRoute: ConfigCompareRoute,
  SchemaRoute: SchemaRouteWithChildren,
  ConfigNameVersionRoute: ConfigNameVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
